modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Move%20Minecarts"
logoFile="icon.png"

[[mods]]
modId="moveminecarts"
version="3.3"
displayName="Move Minecarts"
displayURL="https://curseforge.com/minecraft/mc-mods/move-minecarts"
authors="Rick South"
description='''Allows players to easily pick up and move minecarts without breaking them.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.moveminecarts]]
    modId="collective"
    mandatory=true
    versionRange="[7.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moveminecarts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "moveminecarts_neoforge.mixins.json"