modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Move%20Minecarts"
logoFile="icon.png"

[[mods]]
modId="moveminecarts"
version="4.0"
displayName="Move Minecarts"
displayURL="https://serilum.com/mod/move-minecarts"
authors="Serilum"
description='''Allows players to easily pick up and move minecarts without breaking them.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.moveminecarts]]
    modId="collective"
    mandatory=true
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.moveminecarts]]
    modId="minecraft"
    mandatory=true
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"
